title: Training - exmaples
renderType: freemarker
dialog: training-example:pages/training
templateScript: /training-example/templates/pages/training.ftl
modelClass: com.raul.casa.TrainingPageModel

#areas:
#  main:
#    type: list
#    availableComponents:
#      textImage:
#        id: training-example:components/listadoOficinas